### ISSUE TITLE
The tool doesn't work..

### ISSUE THREAD

**Issue by michaelfyc** [wuhan005/icppp#1]
My `conf.toml`:

![image](https://user-images.githubusercontent.com/45136049/71765826-dfa21380-2f33-11ea-946e-0935e1f3f232.png)

My command:

![image](https://user-images.githubusercontent.com/45136049/71765833-04968680-2f34-11ea-96e5-5387855083f2.png)

The page looks very nice, but the ICP information cannot be found anywhere.

![image](https://user-images.githubusercontent.com/45136049/71765840-37407f00-2f34-11ea-8e3f-37f42357f84d.png)

Where did I do wrong?  

Incidentally, the application is running under debug mode. No big deal.

**Comment by wuhan005** [comment]
Can you provide the URL which you visited in your browser?

**Comment by michaelfyc** [comment]
http://michaelsblog.top:9315.

**Comment by wuhan005** [comment]
Fixed in [commit](https://github.com/wuhan005/icppp/commit/d12e527b5a19fa774cc5a55b7ad688f153c6749e)
Please update the docker image and recreate the container again.

**Comment by michaelfyc** [comment]
It works perfectly right now! Thanks a lot!
