### ISSUE TITLE
公安备案地址无法访问，请更换

### ISSUE THREAD

**Issue by ZhaoTing1993** [wuhan005/icppp#2]
template/index.tpl 
`<p><a href="http://www.beian.miit.gov.cn/" rel="nofollow">{{ .icp }}</a></p>`
地址已失效，正确的公安备案地址
http://www.beian.gov.cn/

**Comment by wuhan005** [comment]
已修复 https://github.com/wuhan005/icppp/commit/36142b882b7fecc90d15cd3fc3a2a84be8bd8e80
